# Generated by Django 5.2.7 on 2025-10-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "activities"},
        ),
        migrations.RenameField(
            model_name="activity",
            old_name="type",
            new_name="activity_type",
        ),
    ]
